### ISSUE TITLE
export pdf error

### ISSUE THREAD

**Issue by junliu-cn** [nicejade/markdown-online-editor#44]
(index):5 Uncaught TypeError: Cannot read property 'insertAdjacentHTML' of null
    at (index):5
(anonymous) @ (index):5
chunk-2d216257.df162628.js:21 Uncaught (in promise) DOMException: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
    at A.<anonymous> (https://markdown.lovejade.cn/js/chunk-2d216257.df162628.js:21:151534)
    at i (https://markdown.lovejade.cn/js/chunk-2d216257.df162628.js:21:1849)
    at Object.next (https://markdown.lovejade.cn/js/chunk-2d216257.df162628.js:21:1144)
    at s (https://markdown.lovejade.cn/js/chunk-2d216257.df162628.js:21:693)
(anonymous) @ chunk-2d216257.df162628.js:21
i @ chunk-2d216257.df162628.js:21
(anonymous) @ chunk-2d216257.df162628.js:21
s @ chunk-2d216257.df162628.js:21
Promise.then (async)
(anonymous) @ chunk-a4189212.a6657841.js:9
h.thenCore @ chunk-a4189212.a6657841.js:9
h.then @ chunk-a4189212.a6657841.js:9
exportAndDownloadPdf @ chunk-5d3ae0d8.23b9f8fb.js:1
onExportBtnClick @ chunk-5d3ae0d8.23b9f8fb.js:1
ie @ app.c10f0d0e.js:34
n @ app.c10f0d0e.js:34
ie @ app.c10f0d0e.js:34
Mn.t.$emit @ app.c10f0d0e.js:34
handleClick @ element.7a4800b8.js:1
ie @ app.c10f0d0e.js:34
n @ app.c10f0d0e.js:34
Fo.o._wrapper @ app.c10f0d0e.js:34
(index):1 The resource https://markdown.lovejade.cn/js/element.7a4800b8.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
(index):1 The resource https://markdown.lovejade.cn/js/app.c10f0d0e.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.

**Comment by nicejade** [comment]
@junliu-cn 
感谢反馈；这是一个已知问题，没有及时解决，后续会安排处理下；您目前可以用如下的方式，导出 PDF。

![Arya - 在线 Markdown 编辑器](https://user-images.githubusercontent.com/15773463/102630259-4b05e500-4187-11eb-8925-8f9f849c52f9.png)

**Comment by nicejade** [comment]
@junliu-cn  抱歉，拖延至今才解决这个问题，已重新部署，详见： [https://markdown.lovejade.cn/](https://markdown.lovejade.cn/)；感谢您的反馈 🤝 。
